### PR TITLE
Reading the Hash Keys from a file

### PR DESCRIPTION
**Pull request by d0vgan**
Reading the Hash Keys from a file "SharpKeys.keys"

### CODE REVIEW

**Comment by randyrants** [comment]
Um, not trying to be thick, what would be the purpose of this?

**Comment by d0vgan** [comment]
It allows to modify the Hash Keys without recompiling the SharpKeys executable.
I.e. any end user will be able to add/modify these mappings according to specific needs.

**Comment by randyrants** [comment]
...except the keys are binary and the UX still has all the default mappings?

I also don't know that I'm all that keen on letting end users change the map.  What I see happening is someone messes around in there without knowing what they are doing which leads to a critical key getting remapped and blaming me for it.  Like "I changed this value and now I can't type my password!" which ends up as email, blog posts, or GitHub messages.  I mean I know that can happen with the app anyway but in the UX it's pretty clear what you're doing... 

I'll think about it and have no objections if you want to branch a repro for it, but I don't know that I'll pull this into the main branch.

**Comment by d0vgan** [comment]
Yes, wide abilities of customization are always a risk :) Though, if the file "SharpKeys.keys" is not given (i.e. does not exist), the behavior remains exactly the same as before.

**Comment by d0vgan** [comment]
I realized I had created this PR from my master. Let me close this PR and create another one instead, from a branch.

**Pull request closed without merging**
