### PR TITLE
Fix repeat key handling in code

### PR DESCRIPTION
**Pull request by igieon**
Fix issue #39 #54

### CODE REVIEW

**Comment by randyrants** [comment]
Has this been tested?  I'm really, REALLY reluctant to build and test something this deep in the code because I could end up remapping the whole keyboard to Space and then I lose the whole machine :)

**Comment by igieon** [comment]
Yes i tested it.

You can also test it and in that way that in previous version hold key and you can see code if you hold volume up and hold you get code in original code E0_4030. Or if you press num 5  and hold you get code E0_3f4c with my change when you hold key you get correct codes E0_30 and 00_4C. Look into documentation which i mention in code  https://msdn.microsoft.com/en-us/library/windows/desktop/ms646280%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by randyrants** [comment]
That's the thing: I don't have a keyboard that showed errors.  Volume, mute, browser, search, mail - all worked fine.  I've merged the source, so we'll see what we see :)

Thanks for taking the time to look into this!

**Comment by igieon** [comment]
To simulate just hold 1 key for 1 min in dialog key press and you can see what is change ;-), but thanks for merge.

**Pull request merged**
